# main.py
"""
Main application that integrates the audit log monitor, rule engine, and LLM analyzer.
This module sets up global state and runs the system in real time.
"""

import threading
from audit_log_monitor import AuditLogMonitor
from rule_engine import RuleEngine
import logging

# Global process map for tracking process states.
process_map = {}

# Path to the audit log file generated by auditd.
LOG_FILE = "sample_auditd_logs/handful_logs"  # Adjust this path as necessary.

# Initialize the Rule Engine with the human-readable rules.
rule_engine = RuleEngine("rules.yaml")

def parse_event_sequence(event_sequence: str):
    """
    Parse a raw event sequence (string) into a list of event dictionaries.
    Each line is assumed to be in the format: "TYPE : key1=value1 key2=value2 ..."
    """
    events = []
    for line in event_sequence.split("\n"):
        line = line.strip()
        if not line:
            continue
        try:
            event_type, payload = line.split(" : ", 1)
            event_dict = {"type": event_type}
            # Split payload into key-value pairs.
            for pair in payload.split(" "):
                if "=" in pair:
                    key, value = pair.split("=", 1)
                    event_dict[key] = value
            events.append(event_dict)
        except Exception as e:
            logging.error(f"Error parsing line: {line} | Exception: {e}")
    return events

def handle_event_sequence(event_sequence: str):
    """
    Handle a complete event sequence by parsing it and passing each event
    to the rule engine for processing.
    """
    events = parse_event_sequence(event_sequence)
    for event in events:
        rule_engine.process_event(event, process_map)

def start_audit_monitor():
    """
    Start the audit log monitor to continuously capture and process event sequences.
    """
    monitor = AuditLogMonitor(LOG_FILE)
    monitor.monitor(handle_event_sequence)

if __name__ == "__main__":
    # Start the audit log monitor on a separate thread.
    monitor_thread = threading.Thread(target=start_audit_monitor, daemon=True)
    monitor_thread.start()

    print("Audit log monitoring system is running. Press Ctrl+C to exit.")
    try:
        while True:
            pass
    except KeyboardInterrupt:
        print("Shutting down system...")